### ISSUE TITLE
Geocode CSO synopses names

### ISSUE THREAD

**Issue by fgregg** [open-city/chicago-river-sewage#24]
We want to be able to say where there is a CSO event. In order to do that we need to geocode the names of the cso locations *as they appear in the cso synopses.*

Unfortunately, these synopses names are not all included in the MWRD Tarp Connection database. In fact, only 63/226 synopses names seem to match the TARP.

This is a problem because we need the "Location" field from the MWRD Tarp dataset to geocode this points.

However, many (most? all?) of the synopses names that do not appear in the MWRD Tarp Connection pdf, do appear on one of  "CSO Representative Monitoring and Reporting Plans" pages, along with a "Location field": 

* http://www.mwrd.org/irj/go/km/docs/documents/MWRD/internet/protecting_the_environment/Combined_Sewer_Overflows/htm/Northside_WRP_CSO_Monitoring_and_Reporting_Plan.htm
* https://www.mwrd.org/irj/go/km/docs/documents/MWRD/internet/protecting_the_environment/Combined_Sewer_Overflows/htm/Stickney_WRP_CSO_Monitoring_and_Reporting_Plan.htm
* https://www.mwrd.org/irj/go/km/docs/documents/MWRD/internet/protecting_the_environment/Combined_Sewer_Overflows/htm/Calumet_WRP_CSO_Monitoring_and_Reporting_Plan.htm

If we have can match the "synopses names" to "Locations," we should then be able to geocode the points by matching against the 

* SSMA data
* the data from the river-viewer app
* and data from the releavant NPDES permits
  * http://iaspub.epa.gov/enviro/ICIS_DETAIL_REPORTS_NPDESID.icis_tst?npdesid=IL0028061&npvalue=1&npvalue=13&npvalue=14&npvalue=3&npvalue=4&npvalue=5&npvalue=6&rvalue=13&npvalue=2&npvalue=7&npvalue=8&npvalue=11&npvalue=12
  * http://iaspub.epa.gov/enviro/ICIS_DETAIL_REPORTS_NPDESID.icis_tst?npdesid=IL0045012&npvalue=1&npvalue=13&npvalue=14&npvalue=3&npvalue=4&npvalue=5&npvalue=6&rvalue=13&npvalue=2&npvalue=7&npvalue=8&npvalue=11&npvalue=12
  * http://iaspub.epa.gov/enviro/ICIS_DETAIL_REPORTS_NPDESID.icis_tst?npdesid=IL0028088&npvalue=1&npvalue=13&npvalue=14&npvalue=3&npvalue=4&npvalue=5&npvalue=6&rvalue=13&npvalue=2&npvalue=7&npvalue=8&npvalue=11&npvalue=12
  * http://iaspub.epa.gov/enviro/ICIS_DETAIL_REPORTS_NPDESID.icis_tst?npdesid=IL0028053&npvalue=1&npvalue=13&npvalue=14&npvalue=3&npvalue=4&npvalue=5&npvalue=6&rvalue=13&npvalue=2&npvalue=7&npvalue=8&npvalue=11&npvalue=12
  * http://iaspub.epa.gov/enviro/ICIS_DETAIL_REPORTS_NPDESID.icis_tst?npdesid=IL0028070&npvalue=1&npvalue=13&npvalue=14&npvalue=3&npvalue=4&npvalue=5&npvalue=6&rvalue=13&npvalue=2&npvalue=7&npvalue=8&npvalue=11&npvalue=12

So, we need to do the following things
- [ ] scrape the CSO Representative Monitoring and Reporting Plans
- [ ] scrape the NPDES permit pages
- [ ] merge

Please call dibs.

**Comment by derekeder** [comment]
no longer needed with #39
