### ISSUE TITLE
update MWRD ESRI layer

### ISSUE THREAD

**Issue by derekeder** [open-city/chicago-river-sewage#42]
MWRD seems to have changed their map again, breaking our real-time checks.

Here's the new map:

http://mwrdgc.maps.arcgis.com/apps/Embed/index.html?webmap=d4972e9006dc4b289f764187f933fc28&extent=-88.6446,41.2429,-86.3979,42.379&zoom=true&scale=true&theme=light

**Comment by derekeder** [comment]
Ok, looks like they updated their URL. I've whittled it down to:

this query on their map works: 

https://utility.arcgis.com/usrsvcs/servers/96bec60971e8401885894c0066fbb881/rest/services/CSO/CSO_Final/FeatureServer/0/query?f=json&where=CSO_EVENT = 'Yes'&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry={"xmin":-9862211.13747117,"ymin":5009377.08570425,"xmax":-9705668.103543205,"ymax":5165920.119632216,"spatialReference":{"wkid":102100,"latestWkid":3857}}&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

this one we're currently using doesn't:

https://utility.arcgis.com/usrsvcs/servers/96bec60971e8401885894c0066fbb881/rest/services/CSO/CSO_Final/FeatureServer/0/query?returnGeometry=true&where=CSO_EVENT="Yes"&outSr=4326&outFields=*&f=geojson

My guess is there are new query parameters that are now required.

**Comment by iandees** [comment]
Single/Double quotes matter in the where clause. This'll return esrijson:

https://utility.arcgis.com/usrsvcs/servers/96bec60971e8401885894c0066fbb881/rest/services/CSO/CSO_Final/FeatureServer/0/query?returnGeometry=true&where=CSO_EVENT=%27Yes%27&outSr=4326&outFields=*&f=json

**Comment by iandees** [comment]
It's not entirely clear to me which scraper code is used here, but if it's written in Python take a look at the Esri dumper code I wrote for OpenAddresses [over here](https://github.com/openaddresses/pyesridump). There's code in there to convert the "EsriJSON" to GeoJSON.

**Comment by derekeder** [comment]
Thx @iandees! Figured out the quotes thing. Got the same query to work.

The way we're pulling this data is via esri-leaflet.js here: https://github.com/open-city/chicago-river-sewage/blob/master/templates/index.html#L160

That library sets an output format of geojson by default, which throws an error for this FeatureLayer. I filed an issue, which they've confirmed as something to fix: https://github.com/Esri/esri-leaflet/issues/876#issuecomment-257165809

**Comment by derekeder** [comment]
Update from MWRD:

> Our current ESRI environment, 10.3.1, does not, and has never supported the GeoJSON format of delivering data.  We are planning on upgrading our current systems to version 10.4.1 before the end of the year.  According to ESRI’s release noted for version 10.4.1 GeoJSOn will be available as an option.  We could look into supplying GeoJSON after the upgrade is completed and determined to be in a stable state.  With this timeline in mind this functionality may be available in early 2017.

> The link is:
> 
> https://utility.arcgis.com/usrsvcs/servers/96bec60971e8401885894c0066fbb881/rest/services/CSO/CSO_Final/FeatureServer/0
> 
> GeoJSON has never been available from an ArcGIS Server service published through ArcGIS online.  It is in the release notes for 10.4.1 as being available. 
> 
> Being dependent on this link has its drawbacks.  If we ever need to re-share or re-publish this service for maintenance reasons will break the link in that the item id will change.  We have no control over this item ID, as it is generated by ArcGIS Online.
> 
> If you can consume the Web Map in AGO, rather than the feature directly, this problem will not ever occur.
> 
> http://mwrdgc.maps.arcgis.com/home/webmap/viewer.html?webmap=d4972e9006dc4b289f764187f933fc28
> 
> After our 10.4.1 upgrade is complete, we are going to look at the GeoJSON capabilities that 10.4.1 is supposed to offer.  We are also going to look at improving our organization’s AGO home page to catalog the services, maps, and apps that we make available.

**Comment by derekeder** [comment]
closed via bae021b
