### ISSUE TITLE
Status Database has not been updated sense June,17th

### ISSUE THREAD

**Issue by chibill** [open-city/chicago-river-sewage#44]
http://istheresewageinthechicagoriver.com/cso-status/?date=07/12/2017

Should report that there was sewage. ( As on that day the site itself did say there was.) Because that was the day with heavy rain fall and flooding.

**Comment by derekeder** [comment]
@chibill thanks for reporting this. the scraper we have to pull the historical data from MWRD is run manually at this point. I just re-ran it and the site is updated.

Closed via b0671c9df2d1d03d19eee9e1001f043f38437d24
